### PR TITLE
IDE-2850: Define react as external library

### PR DESCRIPTION
**Pull request by qtran-n4**

### CODE REVIEW

**Comment by qtran-n4** [comment]
@dbo Please review this. We are going to merge this after you come back.

**Review by dbo — APPROVED** [review]
@qtran-n4 Please wait for the most recent update to React 16.

👍  with that

**Comment by qtran-n4** [comment]
@dbo I have updated the React.n4jd definition file. Please have a second look. Thanks!

**Review by dbo — APPROVED** [review]
👍

**Pull request merged**
